UI rebrush
zugvoegel-festival/schwarmplaner pull request #27
Opened 2023-01-03 10:20 UTC by CivanErbay

2023-01-03 11:58 UTC, manuliner requested changes

2023-01-03 11:58 UTC, manuliner commented on frontend-vue/public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap" rel="stylesheet">
please use local hosted google fonts

2023-01-03 11:58 UTC, manuliner commented on frontend-vue/src/main.js
> +import VueCookies from "vue3-cookies";
do we need cookies for technical reasons? we could use local storage for persistent data.

2023-01-04 11:36 UTC, CivanErbay commented on frontend-vue/public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap" rel="stylesheet">
font now locally embedded

2023-01-04 11:36 UTC, CivanErbay commented on frontend-vue/src/main.js
> +import VueCookies from "vue3-cookies";
cookie-lib deleted // local storage should be enough

2023-01-04 11:53 UTC, manuliner approved these changes

2023-01-04 11:53 UTC, merged